KS-22-4 imitate the data loading process
An-Frolova/KotlinSprint pull request #112
Opened 2024-12-19 08:13 UTC by An-Frolova

2024-12-19 13:32 UTC, ievetrovdev requested changes

2024-12-19 13:32 UTC, ievetrovdev commented on src/main/kotlin/lesson_22/lesson22_task4.kt
> +        var currentState = mainScreenState.copy(data = null)
Немного не так
1. стейт не нужно в коснтрукторе объявлять, так как он привязывается напрямую с моделью. Объяви в теле класса
2. При изменени сейфа его ненужно создавать новый, все изменения происходит с 1 объектом(стейтом). Только по нему будут видный изменения на экране

2024-12-20 06:52 UTC, An-Frolova commented
А это "все изменения происходит с 1 объектом(стейтом).", не противоречит вот этой части задачи: "При изменении состояния загрузки необходимо создать новый объект MainScreenState, скопировав текущее состояние и изменив значение поля isLoading."? Я иначе не понимаю, как это реализовать

2024-12-20 13:29 UTC, ievetrovdev approved these changes

2024-12-21 14:02 UTC, merged