KS-11-5 Add Forum class with Builder pattern
An-Frolova/KotlinSprint pull request #55
Opened 2024-12-04 06:31 UTC by An-Frolova

2024-12-04 19:33 UTC, ievetrovdev requested changes

2024-12-04 19:33 UTC, ievetrovdev commented on src/main/kotlin/lesson_11/lesson11_task5.kt
> +    class ForumMessageBuilder() {
Билдеры в таком формате обычно несколько иначе реализуются, давай лучше перенесем логику создания сообщений и пользователей в класс форума. Так мы воплотим паттерн, без создания лишних классов

2024-12-05 07:21 UTC, An-Frolova commented
Так? В данном случае это тоже считается реализацией паттерна?

2024-12-06 08:46 UTC, ievetrovdev approved these changes
Да. все верно теперь, отличное решение!

2024-12-06 10:36 UTC, merged