KS-17-1 add getters and setter to class Quiz
An-Frolova/KotlinSprint pull request #82
Opened 2024-12-10 07:46 UTC by An-Frolova

2024-12-10 07:53 UTC, An-Frolova commented
Увидела, что в конструкторе должны быть "свойства"

2024-12-10 19:28 UTC, ievetrovdev requested changes

2024-12-10 19:28 UTC, ievetrovdev commented on src/main/kotlin/lesson_17/lesson17_task1.kt
> +    var answer: String,
Предлагаю сделать согласно ТЗ. Свойства лучше задавать объекту прямо при его создании – в основном конструкторе. Затем будем этим же свойством инициализировать объявленную в теле класса переменную, где явно для нее прописываем сеттер и геттер. Вспомни как в 12-3 уроке использовался такой же подход.

2024-12-11 18:06 UTC, ievetrovdev approved these changes
Теперь все верно, отлично!

2024-12-12 05:58 UTC, merged