KS-17-2 add disallow variable change with setter
An-Frolova/KotlinSprint pull request #83
Opened 2024-12-10 09:53 UTC by An-Frolova

2024-12-10 10:59 UTC, An-Frolova commented
Наверное, так более правильно

2024-12-10 19:30 UTC, ievetrovdev requested changes

2024-12-10 19:30 UTC, ievetrovdev commented on src/main/kotlin/lesson_17/lesson17_task2.kt
> +    private var seaport: String,
Доступ публичный, ограничение на изменение значения имени только через  set

2024-12-11 18:06 UTC, ievetrovdev approved these changes
Теперь все верно, отлично!

2024-12-12 05:59 UTC, merged