KS-2-4 game bonus calculation
An-Frolova/KotlinSprint pull request #9
Opened 2024-11-13 09:05 UTC by An-Frolova

2024-11-14 21:18 UTC, ievetrovdev requested changes

2024-11-14 21:18 UTC, ievetrovdev commented on src/main/kotlin/lesson_2/lesson2_task4.kt
> +    val buff = 0.2f
Для возможности гибкой работы с кодом, следует инициализировать согласно ТЗ проценты целым числом 20. И уже потом производить вычисление процентов. Таким образом, если нужен будет другой процент, достаточно будет поменять значение в одном месте.

2024-11-15 22:44 UTC, ievetrovdev requested changes

2024-11-15 22:44 UTC, ievetrovdev commented on src/main/kotlin/lesson_2/lesson2_task4.kt
> +    val buffForCalculations = buffInPercentage * 0.01
0.01 это магическое число, давай вынесем его в константу

2024-11-16 05:56 UTC, An-Frolova commented
Возникли затруднения с наименованием константы, так, чтобы из кода было понятно, для чего она. Надеюсь, такой вариант корректный

2024-11-16 23:38 UTC, ievetrovdev approved these changes
Все верно, отлично!

2024-11-17 10:36 UTC, merged